spring:
  application:
    name:learning-spring-cloud-config-server-application
  cloud:
    config:
      server:
        git:
          uri:https://github.com/uday8899/environment-variable-repo.git

server:
  port: 8888
